# Feature Extraction From Short Temporal Sequences for Clustering {#diabfoot}

```{r 08-setup, eval = FALSE, echo = FALSE, cache = TRUE, message = FALSE, results='asis'}
source("code/00-chapter-start-bib.R")
print_bib(c("Niemann:CBMS2016",
            "Niemann:PONE2016", 
            "Niemann:EBioMedicine2020")
          , bib = bib)
```

:::: {.infobox .chapter-summary data-latex="{tasks.pdf}"}

#### Brief Chapter Summary {-}

We present an approach to build representations from short temporal sequences via clustering by the example of pressure- and posture-dependent plantar temperature and pressure in patients with diabetic foot syndrome. 

::::

:::: {.infobox .chapter-literature data-latex=""}
This chapter is partly based on:

- Uli Niemann, Myra Spiliopoulou, Fred Samland, Thorsten Szczepanski, Jens Grützner, Antao Ming, Juliane Kellersmann, Jan Malanowski, Silke Klose, and Peter R. Mertens. "Learning Pressure Patterns for Patients with Diabetic Foot Syndrome". In: _Proc. of IEEE Int. Symposium on Computer-Based Medical Systems (CBMS)_. 2016, pp. 54--59. DOI: [10.1109/CBMS.2016.31](https://doi.org/10.1109%2FCBMS.2016.31).
- Uli Niemann, Myra Spiliopoulou, Thorsten Szczepanski, Fred Samland, Jens Grützner, Dominik Senk, Antao Ming, Juliane Kellersmann, Jan Malanowski, Silke Klose, and Peter R. Mertens. "Comparative Clustering of Plantar Pressure Distributions in Diabetics with Polyneuropathy May Be Applied to Reveal Inappropriate Biomechanical Stress". In: _PLOS ONE_ 11.8 (2016), pp. 1--12. DOI: [10.1371/journal.pone.0161326](https://doi.org/10.1371%2Fjournal.pone.0161326).
- Uli Niemann, Myra Spiliopoulou, Jan Malanowski, Juliane Kellersmann, Thorsten Szczepanski, Silke Klose, Eirini Dedonaki, Isabell Walter, Antao Ming, and Peter R. Mertens. "Plantar temperatures in stance position: A comparative study with healthy volunteers and diabetes patients diagnosed with sensoric neuropathy". In: _EBioMedicine_ 54 (2020), p. 102712. DOI: [10.1016/j.ebiom.2020.102712](https://doi.org/10.1016%2Fj.ebiom.2020.102712).

::::

<!-- ## Motivation and Comparison to Related Work {#diabfoot-intro} -->

**to be written**

<!-- ## Comparing Differences in Feature Importance between Two Subpopulations {#gender-measure} -->

<!-- **to be written** -->

<!-- ## Workflow {#gender-workflow} -->

<!-- ### Learning Tasks -->

<!-- **to be written** -->

<!-- ### Model Evaluation and Hyperparameter Tuning -->

<!-- ## Results {#gender-results} -->

<!-- **to be written** -->

<!-- ## Conclusions on Subpopulation-Specific Differences in Feature Importance {#gender-conclusions} -->

<!-- **to be written** -->


<!-- TODO: move this paragraph  -->
<!-- \subsubsection{CBMS16} -->
<!-- **Clustering.**  -->
<!-- Clustering algorithms are applied to a variety of application domains. -->
<!-- For example, clustering is traditionally used for the identification of patient groups, who apply pressure on their feet in a similar way&nbsp;[@BennettsEtAl:Biomechanics2013; @DeCockEtAl:FootTypeClusteringPlantarPressure2006; @DeschampsEtAL:KMeansDiabeticFoot2013; @GiacomozziMartelli:PeakPressure2006], whereby k-means is the typically the algorithm of choice. -->
<!-- In&nbsp;[@GiacomozziMartelli:PeakPressure2006], Giacomozzi and Martelli -->
<!-- studied the plantar pressure curves of patients with diabetic foot and of control persons, and clustered them on the similarity of the curves with respect to shape and amplitude. They juxtaposed the clusters with respect to predefined groups: for instance, all persons of the group with increased peak pressure and muscle weakness and/or limited mobility of the joints were in one cluster&nbsp;[@GiacomozziMartelli:PeakPressure2006].  -->
<!-- However, each cluster contained persons from many groups. -->
<!-- Deschamps et al. recorded walking trials for patients and controls and studied the relative regional impulses recorded in six forefoot regions&nbsp;[@DeschampsEtAL:KMeansDiabeticFoot2013]: similarly to&nbsp;[@GiacomozziMartelli:PeakPressure2006], they also found one cluster that consists only of diabetic patients.  -->
<!-- Other scholars focused on patients only and strived to understand the variability of pressure distributions among patients and to stratify the patients on plantar pressure similarity. -->
<!-- De Cock et al. studied the pressure distributions recorded during jogging, whereby they concentrated on recordings of the six forefoot regions&nbsp;[@DeCockEtAl:FootTypeClusteringPlantarPressure2006]: they used k-means with k=4 and then -->
<!-- compared differences in peak pressure and in regional impulse among the identified clusters. -->
<!-- Bennetts et al. studied how patients applied pressure when they stood, and performed clustering on peak pressure  -->
<!-- distinguishing among seven plantar regions&nbsp;[@BennettsEtAl:Biomechanics2013].  -->
<!-- They compared the clusters on mean peak pressure and studied how the number of clusters k affected the results. -->
<!-- Similarly to &nbsp;[@BennettsEtAl:Biomechanics2013,DeCockEtAl:FootTypeClusteringPlantarPressure2006], we focus on patient stratification with clustering. As in &nbsp;[@BennettsEtAl:Biomechanics2013,GiacomozziMartelli:PeakPressure2006], we consider all regions of the foot, not forefoot only. Unlike all aforementioned methods who determined similarity in a single way and then used $k$-means for clustering, we consider alternative ways of modeling similarity with respect to pressure, we juxtapose the clusters built by different clustering algorithms in terms of quality, and -->
<!-- we deliver visualization aids for the inspection of the most representative instance (patient foot) in each cluster. -->
<!-- The tasks of modeling similarity, learning clusters with different algorithms, comparing them and inspecting the results, constitute a complete mining workflow. In &nbsp;[@GlasserEtAl:CBMS13,NiemannEtAl:CBMS15], we proposed workflows that encompass the specification of similarity between instances, the tuning of clustering algorithms (in &nbsp;[@NiemannEtAl:CBMS15]) and the assessment of quality. However, these workflows concern the juxtaposition of patients to healthy people, while here we concentrate on the stratification of patients only and build the workflow accordingly. -->
